In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
pd.options.display.max_columns = 999

In [3]:
df = pd.read_csv('resources/school-ela-results-2013-18-ALL.csv', skiprows=7)
df.head()

,Unnamed: 0,DBN,School Name,Grade,Year,Category,Number Tested,Mean Scale Score,#,%,#.1,%.1,#.2,%.2,#.3,%.3,#.4,%.4
0,01M01532013All Students,01M015,P.S. 015 Roberto Clemente,3,2013,All Students,27,289,14,51.9,11,40.7,2,7.4,0,0.0,2,7.4
1,01M01532014All Students,01M015,P.S. 015 Roberto Clemente,3,2014,All Students,18,285,10,55.6,8,44.4,0,0.0,0,0.0,0,0.0
2,01M01532015All Students,01M015,P.S. 015 Roberto Clemente,3,2015,All Students,16,282,9,56.3,5,31.3,2,12.5,0,0.0,2,12.5
3,01M01532016All Students,01M015,P.S. 015 Roberto Clemente,3,2016,All Students,20,293,10,50.0,6,30.0,4,20.0,0,0.0,4,20.0
4,01M01532017All Students,01M015,P.S. 015 Roberto Clemente,3,2017,All Students,27,302,10,37.0,8,29.6,7,25.9,2,7.4,9,33.3

Rename the columns for easier access.

In [4]:
new_cols = ['sort', 'dbn', 'school_name', 'grade', 'year', 'category', 'num_tested', 'mean_score', 'num_1', 'perc_1', 'num_2', 'perc_2', 'num_3', 'perc_3', 'num_4', 'perc_4', 'num_34', 'perc_34']
cols_map = {df.columns[i]: new_cols[i] for i in range(len(df.columns))}
df.rename(index=str, columns=cols_map, inplace=True)
df.head()

,sort,dbn,school_name,grade,year,category,num_tested,mean_score,num_1,perc_1,num_2,perc_2,num_3,perc_3,num_4,perc_4,num_34,perc_34
0,01M01532013All Students,01M015,P.S. 015 Roberto Clemente,3,2013,All Students,27,289,14,51.9,11,40.7,2,7.4,0,0.0,2,7.4
1,01M01532014All Students,01M015,P.S. 015 Roberto Clemente,3,2014,All Students,18,285,10,55.6,8,44.4,0,0.0,0,0.0,0,0.0
2,01M01532015All Students,01M015,P.S. 015 Roberto Clemente,3,2015,All Students,16,282,9,56.3,5,31.3,2,12.5,0,0.0,2,12.5
3,01M01532016All Students,01M015,P.S. 015 Roberto Clemente,3,2016,All Students,20,293,10,50.0,6,30.0,4,20.0,0,0.0,4,20.0
4,01M01532017All Students,01M015,P.S. 015 Roberto Clemente,3,2017,All Students,27,302,10,37.0,8,29.6,7,25.9,2,7.4,9,33.3

No missing data

In [5]:
df.shape[0] - df.count()

sort           0
dbn            0
school_name    0
grade          0
year           0
category       0
num_tested     0
mean_score     0
num_1          0
perc_1         0
num_2          0
perc_2         0
num_3          0
perc_3         0
num_4          0
perc_4         0
num_34         0
perc_34        0
dtype: int64

***

Create a dataframe for each year and grade, and merge them on dbn.

In [50]:
grades = df['grade'].unique()
years = df['year'].unique()
init_cols = {i: i + '_3_2013' for i in df.columns if i != 'dbn'}
for i,g in enumerate(grades):
    for j,y in enumerate(years):
        if i == j == 0:
            temp = df[df['year'] == y]
            df_merged = temp[temp['grade'] == g]
        else:
            temp = df[df['year'] == y]
            df_merged = pd.merge(df_merged, temp[temp['grade'] == g], how='outer', on='dbn', suffixes=['', '_{}_{}'.format(grades[i], years[j])])
df_merged.rename(index=str, columns=init_cols, inplace=True)
df_merged.head()

,sort_3_2013,dbn,school_name_3_2013,grade_3_2013,year_3_2013,category_3_2013,num_tested_3_2013,mean_score_3_2013,num_1_3_2013,perc_1_3_2013,num_2_3_2013,perc_2_3_2013,num_3_3_2013,perc_3_3_2013,num_4_3_2013,perc_4_3_2013,num_34_3_2013,perc_34_3_2013,sort_3_2014,school_name_3_2014,grade_3_2014,year_3_2014,category_3_2014,num_tested_3_2014,mean_score_3_2014,num_1_3_2014,perc_1_3_2014,num_2_3_2014,perc_2_3_2014,num_3_3_2014,perc_3_3_2014,num_4_3_2014,perc_4_3_2014,num_34_3_2014,perc_34_3_2014,sort_3_2015,school_name_3_2015,grade_3_2015,year_3_2015,category_3_2015,num_tested_3_2015,mean_score_3_2015,num_1_3_2015,perc_1_3_2015,num_2_3_2015,perc_2_3_2015,num_3_3_2015,perc_3_3_2015,num_4_3_2015,perc_4_3_2015,num_34_3_2015,perc_34_3_2015,sort_3_2016,school_name_3_2016,grade_3_2016,year_3_2016,category_3_2016,num_tested_3_2016,mean_score_3_2016,num_1_3_2016,perc_1_3_2016,num_2_3_2016,perc_2_3_2016,num_3_3_2016,perc_3_3_2016,num_4_3_2016,perc_4_3_2016,num_34_3_2016,perc_34_3_2016,sort_3_2017,school_name_3_2017,grade_3_2017,year_3_2017,category_3_2017,num_tested_3_2017,mean_score_3_2017,num_1_3_2017,perc_1_3_2017,num_2_3_2017,perc_2_3_2017,num_3_3_2017,perc_3_3_2017,num_4_3_2017,perc_4_3_2017,num_34_3_2017,perc_34_3_2017,sort_3_2018,school_name_3_2018,grade_3_2018,year_3_2018,category_3_2018,num_tested_3_2018,mean_score_3_2018,num_1_3_2018,perc_1_3_2018,num_2_3_2018,perc_2_3_2018,num_3_3_2018,perc_3_3_2018,num_4_3_2018,perc_4_3_2018,num_34_3_2018,perc_34_3_2018,sort_4_2013,school_name_4_2013,grade_4_2013,year_4_2013,category_4_2013,num_tested_4_2013,mean_score_4_2013,num_1_4_2013,perc_1_4_2013,num_2_4_2013,perc_2_4_2013,num_3_4_2013,perc_3_4_2013,num_4_4_2013,perc_4_4_2013,num_34_4_2013,perc_34_4_2013,sort_4_2014,school_name_4_2014,grade_4_2014,year_4_2014,category_4_2014,num_tested_4_2014,mean_score_4_2014,num_1_4_2014,perc_1_4_2014,num_2_4_2014,perc_2_4_2014,num_3_4_2014,perc_3_4_2014,num_4_4_2014,perc_4_4_2014,num_34_4_2014,perc_34_4_2014,sort_4_2015,school_name_4_2015,grade_4_2015,year_4_2015,category_4_2015,num_tested_4_2015,mean_score_4_2015,num_1_4_2015,perc_1_4_2015,num_2_4_2015,perc_2_4_2015,num_3_4_2015,perc_3_4_2015,num_4_4_2015,perc_4_4_2015,num_34_4_2015,perc_34_4_2015,sort_4_2016,school_name_4_2016,grade_4_2016,year_4_2016,category_4_2016,num_tested_4_2016,mean_score_4_2016,num_1_4_2016,perc_1_4_2016,num_2_4_2016,perc_2_4_2016,num_3_4_2016,perc_3_4_2016,num_4_4_2016,perc_4_4_2016,num_34_4_2016,perc_34_4_2016,sort_4_2017,school_name_4_2017,grade_4_2017,year_4_2017,category_4_2017,num_tested_4_2017,mean_score_4_2017,num_1_4_2017,perc_1_4_2017,num_2_4_2017,perc_2_4_2017,num_3_4_2017,perc_3_4_2017,num_4_4_2017,perc_4_4_2017,num_34_4_2017,perc_34_4_2017,sort_4_2018,school_name_4_2018,grade_4_2018,year_4_2018,category_4_2018,num_tested_4_2018,mean_score_4_2018,num_1_4_2018,perc_1_4_2018,num_2_4_2018,perc_2_4_2018,num_3_4_2018,perc_3_4_2018,num_4_4_2018,perc_4_4_2018,num_34_4_2018,perc_34_4_2018,sort_5_2013,school_name_5_2013,grade_5_2013,year_5_2013,category_5_2013,num_tested_5_2013,mean_score_5_2013,num_1_5_2013,perc_1_5_2013,num_2_5_2013,perc_2_5_2013,num_3_5_2013,perc_3_5_2013,num_4_5_2013,perc_4_5_2013,num_34_5_2013,perc_34_5_2013,sort_5_2014,school_name_5_2014,grade_5_2014,year_5_2014,category_5_2014,num_tested_5_2014,mean_score_5_2014,num_1_5_2014,perc_1_5_2014,num_2_5_2014,perc_2_5_2014,num_3_5_2014,perc_3_5_2014,num_4_5_2014,perc_4_5_2014,num_34_5_2014,perc_34_5_2014,sort_5_2015,school_name_5_2015,grade_5_2015,year_5_2015,category_5_2015,num_tested_5_2015,mean_score_5_2015,num_1_5_2015,perc_1_5_2015,num_2_5_2015,perc_2_5_2015,num_3_5_2015,perc_3_5_2015,num_4_5_2015,perc_4_5_2015,num_34_5_2015,perc_34_5_2015,sort_5_2016,school_name_5_2016,grade_5_2016,year_5_2016,category_5_2016,num_tested_5_2016,mean_score_5_2016,num_1_5_2016,perc_1_5_2016,num_2_5_2016,perc_2_5_2016,num_3_5_2016,perc_3_5_2016,num_4_5_2016,perc_4_5_2016,num_34_5_2016,perc_34_5_2016,sort_5_2017,school_name_5_2017,grade_5_2017,year_5_2017,category_5_2017,num_tested_5_2017,mean_score_5_2017,num_1_5_2017,perc_1_5_2017,num_2_5_2017,perc_2_5_2017,num_3_5_2017,perc_3_5_2017,num_4_5_2017,perc_4_5_2017,num_34_5_2017,perc_34_5_2017,sort_5_2018,school_name_5_2018,grade_5_2018,year_5_2018,category_5_2018,num_tested_5_2018,mean_score_5_2018,num_1_5_2018,perc_1_5_2018,num_2_5_2018,perc_2_5_2018,num_3_5_2018,perc_3_5_2018,num_4_5_2018,perc_4_5_2018,num_34_5_2018,perc_34_5_2018,sort_All Grades_2013,school_name_All Grades_2013,grade_All Grades_2013,year_All Grades_2013,category_All Grades_2013,num_tested_All Grades_2013,mean_score_All Grades_2013,num_1_All Grades_2013,perc_1_All Grades_2013,num_2_All Grades_2013,perc_2_All Grades_2013,num_3_All Grades_2013,perc_3_All Grades_2013,num_4_All Grades_2013,perc_4_All Grades_2013,num_34_All Grades_2013,perc_34_All Grades_2013,sort_All Grades_2014,school_name_All Grades_2014,grade_All Grades_2014,year_All Grades_2014,category_All Grades_2014,num_tested_All Grades_2014,mean_score_All Grades_2014,num_1_All Grades_2014,perc_1_All Grades_2014,num_2_All Grades_2014,perc_2_All Grades_2014,num_3_All Grades_2014,perc_3_All Grades_2014,num_4_All Grades_2014,perc_4_All Grades_2014,num_34_All Grades_2014,perc_34_All Grades_2014,sort_All Grades_2015,school_name_All Grades_2015,grade_All Grades_2015,year_All Grades_2015,category_All Grades_2015,num_tested_All Grades_2015,mean_score_All Grades_2015,num_1_All Grades_2015,perc_1_All Grades_2015,num_2_All Grades_2015,perc_2_All Grades_2015,num_3_All Grades_2015,perc_3_All Grades_2015,num_4_All Grades_2015,perc_4_All Grades_2015,num_34_All Grades_2015,perc_34_All Grades_2015,sort_All Grades_2016,school_name_All Grades_2016,grade_All Grades_2016,year_All Grades_2016,category_All Grades_2016,num_tested_All Grades_2016,mean_score_All Grades_2016,num_1_All Grades_2016,perc_1_All Grades_2016,num_2_All Grades_2016,perc_2_All Grades_2016,num_3_All Grades_2016,perc_3_All Grades_2016,num_4_All Grades_2016,perc_4_All Grades_2016,num_34_All Grades_2016,perc_34_All Grades_2016,sort_All Grades_2017,school_name_All Grades_2017,grade_All Grades_2017,year_All Grades_2017,category_All Grades_2017,num_tested_All Grades_2017,mean_score_All Grades_2017,num_1_All Grades_2017,perc_1_All Grades_2017,num_2_All Grades_2017,perc_2_All Grades_2017,num_3_All Grades_2017,perc_3_All Grades_2017,num_4_All Grades_2017,perc_4_All Grades_2017,num_34_All Grades_2017,perc_34_All Grades_2017,sort_All Grades_2018,school_name_All Grades_2018,grade_All Grades_2018,year_All Grades_2018,category_All Grades_2018,num_tested_All Grades_2018,mean_score_All Grades_2018,num_1_All Grades_2018,perc_1_All Grades_2018,num_2_All Grades_2018,perc_2_All Grades_2018,num_3_All Grades_2018,perc_3_All Grades_2018,num_4_All Grades_2018,perc_4_All Grades_2018,num_34_All Grades_2018,perc_34_All Grades_2018,sort_6_2013,school_name_6_2013,grade_6_2013,year_6_2013,category_6_2013,num_tested_6_2013,mean_score_6_2013,num_1_6_2013,perc_1_6_2013,num_2_6_2013,perc_2_6_2013,num_3_6_2013,perc_3_6_2013,num_4_6_2013,perc_4_6_2013,num_34_6_2013,perc_34_6_2013,sort_6_2014,school_name_6_2014,grade_6_2014,year_6_2014,category_6_2014,num_tested_6_2014,mean_score_6_2014,num_1_6_2014,perc_1_6_2014,num_2_6_2014,perc_2_6_2014,num_3_6_2014,perc_3_6_2014,num_4_6_2014,perc_4_6_2014,num_34_6_2014,perc_34_6_2014,sort_6_2015,school_name_6_2015,grade_6_2015,year_6_2015,category_6_2015,num_tested_6_2015,mean_score_6_2015,num_1_6_2015,perc_1_6_2015,num_2_6_2015,perc_2_6_2015,num_3_6_2015,perc_3_6_2015,num_4_6_2015,perc_4_6_2015,num_34_6_2015,perc_34_6_2015,sort_6_2016,school_name_6_2016,grade_6_2016,year_6_2016,category_6_2016,num_tested_6_2016,mean_score_6_2016,num_1_6_2016,perc_1_6_2016,num_2_6_2016,perc_2_6_2016,num_3_6_2016,perc_3_6_2016,num_4_6_2016,perc_4_6_2016,num_34_6_2016,perc_34_6_2016,sort_6_2017,school_name_6_2017,grade_6_2017,year_6_2017,category_6_2017,num_tested_6_2017,mean_score_6_2017,num_1_6_2017,perc_1_6_2017,num_2_6_2017,perc_2_6_2017,num_3_6_2017,perc_3_6_2017,num_4_6_2017,perc_4_6_2017,num_34_6_2017,perc_34_6_2017,sort_6_2018,school_name_6_2018,grade_6_2018,year_6_2018,category_6_2018,num_tested_6_2018,mean_score_6_2018,num_1_6_2018,perc_1_6_2018,num_2_6_2018,perc_2_6_2018,num_3_6_2018,perc_3_6_2018,num_4_6_2018,perc_4_6_2018,num_34_6_2018,perc_34_6_2018,sort_7_2013,school_name_7_2013,grade_7_2013,year_7_2013,category_7_2013,num_tested_7_2013,mean_score_7_2013,num_1_7_2013,perc_1_7_2013,num_2_7_2013,perc_2_7_2013,num_3_7_2013,perc_3_7_2013,num_4_7_2013,perc_4_7_2013,num_34_7_2013,perc_34_7_2013,sort_7_2014,school_name_7_2014,grade_7_2014,year_7_2014,category_7_2014,num_tested_7_2014,mean_score_7_2014,num_1_7_2014,perc_1_7_2014,num_2_7_2014,perc_2_7_2014,num_3_7_2014,perc_3_7_2014,num_4_7_2014,perc_4_7_2014,num_34_7_2014,perc_34_7_2014,sort_7_2015,school_name_7_2015,grade_7_2015,year_7_2015,category_7_2015,num_tested_7_2015,mean_score_7_2015,num_1_7_2015,perc_1_7_2015,num_2_7_2015,perc_2_7_2015,num_3_7_2015,perc_3_7_2015,num_4_7_2015,perc_4_7_2015,num_34_7_2015,perc_34_7_2015,sort_7_2016,school_name_7_2016,grade_7_2016,year_7_2016,category_7_2016,num_tested_7_2016,mean_score_7_2016,num_1_7_2016,perc_1_7_2016,num_2_7_2016,perc_2_7_2016,num_3_7_2016,perc_3_7_2016,num_4_7_2016,perc_4_7_2016,num_34_7_2016,perc_34_7_2016,sort_7_2017,school_name_7_2017,grade_7_2017,year_7_2017,category_7_2017,num_tested_7_2017,mean_score_7_2017,num_1_7_2017,perc_1_7_2017,num_2_7_2017,perc_2_7_2017,num_3_7_2017,perc_3_7_2017,num_4_7_2017,perc_4_7_2017,num_34_7_2017,perc_34_7_2017,sort_7_2018,school_name_7_2018,grade_7_2018,year_7_2018,category_7_2018,num_tested_7_2018,mean_score_7_2018,num_1_7_2018,perc_1_7_2018,num_2_7_2018,perc_2_7_2018,num_3_7_2018,perc_3_7_2018,num_4_7_2018,perc_4_7_2018,num_34_7_2018,perc_34_7_2018,sort_8_2013,school_name_8_2013,grade_8_2013,year_8_2013,category_8_2013,num_tested_8_2013,mean_score_8_2013,num_1_8_2013,perc_1_8_2013,num_2_8_2013,perc_2_8_2013,num_3_8_2013,perc_3_8_2013,num_4_8_2013,perc_4_8_2013,num_34_8_2013,perc_34_8_2013,sort_8_2014,school_name_8_2014,grade_8_2014,year_8_2014,category_8_2014,num_tested_8_2014,mean_score_8_2014,num_1_8_2014,perc_1_8_2014,num_2_8_2014,perc_2_8_2014,num_3_8_2014,perc_3_8_2014,num_4_8_2014,perc_4_8_2014,num_34_8_2014,perc_34_8_2014,sort_8_2015,school_name_8_2015,grade_8_2015,year_8_2015,category_8_2015,num_tested_8_2015,mean_score_8_2015,num_1_8_2015,perc_1_8_2015,num_2_8_2015,perc_2_8_2015,num_3_8_2015,perc_3_8_2015,num_4_8_2015,perc_4_8_2015,num_34_8_2015,perc_34_8_2015,sort_8_2016,school_name_8_2016,grade_8_2016,year_8_2016,category_8_2016,num_tested_8_2016,mean_score_8_2016,num_1_8_2016,perc_1_8_2016,num_2_8_2016,perc_2_8_2016,num_3_8_2016,perc_3_8_2016,num_4_8_2016,perc_4_8_2016,num_34_8_2016,perc_34_8_2016,sort_8_2017,school_name_8_2017,grade_8_2017,year_8_2017,category_8_2017,num_tested_8_2017,mean_score_8_2017,num_1_8_2017,perc_1_8_2017,num_2_8_2017,perc_2_8_2017,num_3_8_2017,perc_3_8_2017,num_4_8_2017,perc_4_8_2017,num_34_8_2017,perc_34_8_2017,sort_8_2018,school_name_8_2018,grade_8_2018,year_8_2018,category_8_2018,num_tested_8_2018,mean_score_8_2018,num_1_8_2018,perc_1_8_2018,num_2_8_2018,perc_2_8_2018,num_3_8_2018,perc_3_8_2018,num_4_8_2018,perc_4_8_2018,num_34_8_2018,perc_34_8_2018
0,01M01532013All Students,01M015,P.S. 015 Roberto Clemente,3,2013.0,All Students,27.0,289,14,51.9,11,40.7,2,7.4,0,0.0,2,7.4,01M01532014All Students,P.S. 015 Roberto Clemente,3,2014.0,All Students,18.0,285,10,55.6,8,44.4,0,0.0,0,0.0,0,0.0,01M01532015All Students,P.S. 015 Roberto Clemente,3,2015.0,All Students,16.0,282,9,56.3,5,31.3,2,12.5,0,0.0,2,12.5,01M01532016All Students,P.S. 015 Roberto Clemente,3,2016.0,All Students,20.0,293,10,50.0,6,30.0,4,20.0,0,0.0,4,20.0,01M01532017All Students,P.S. 015 Roberto Clemente,3,2017.0,All Students,27.0,302,10,37.0,8,29.6,7,25.9,2,7.4,9,33.3,01M01532018All Students,P.S. 015 Roberto Clemente,3,2018.0,All Students,20.0,613,0,0.0,4,20.0,13,65.0,3,15.0,16,80.0,01M01542013All Students,P.S. 015 Roberto Clemente,4,2013.0,All Students,20.0,278,8,40.0,11,55.0,1,5.0,0,0.0,1,5.0,01M01542014All Students,P.S. 015 Roberto Clemente,4,2014.0,All Students,24.0,284,13,54.2,10,41.7,1,4.2,0,0.0,1,4.2,01M01542015All Students,P.S. 015 Roberto Clemente,4,2015.0,All Students,16.0,288,5,31.3,11,68.8,0,0.0,0,0.0,0,0.0,01M01542016All Students,P.S. 015 Roberto Clemente,4,2016.0,All Students,15.0,298,5,33.3,7,46.7,3,20.0,0,0.0,3,20.0,01M01542017All Students,P.S. 015 Roberto Clemente,4,2017.0,All Students,23.0,314,1,4.3,12,52.2,9,39.1,1,4.3,10,43.5,01M01542018All Students,P.S. 015 Roberto Clemente,4,2018.0,All Students,26.0,611,0,0.0,8,30.8,12,46.2,6,23.1,18,69.2,01M01552013All Students,P.S. 015 Roberto Clemente,5,2013.0,All Students,24.0,284,12,50.0,11,45.8,1,4.2,0,0.0,1,4.2,01M01552014All Students,P.S. 015 Roberto Clemente,5,2014.0,All Students,21.0,268,15,71.4,5,23.8,0,0.0,1,4.8,1,4.8,01M01552015All Students,P.S. 015 Roberto Clemente,5,2015.0,All Students,24.0,281,14,58.3,9,37.5,1,4.2,0,0.0,1,4.2,01M01552016All Students,P.S. 015 Roberto Clemente,5,2016.0,All Students,16.0,288,8,50.0,5,31.3,3,18.8,0,0.0,3,18.8,01M01552017All Students,P.S. 015 Roberto Clemente,5,2017.0,All Students,17.0,310,1,5.9,11,64.7,5,29.4,0,0.0,5,29.4,01M01552018All Students,P.S. 015 Roberto Clemente,5,2018.0,All Students,21.0,607,5,23.8,5,23.8,6,28.6,5,23.8,11,52.4,01M015All Grades2013All Students,P.S. 015 Roberto Clemente,All Grades,2013.0,All Students,71.0,284,34,47.9,33,46.5,4,5.6,0,0.0,4,5.6,01M015All Grades2014All Students,P.S. 015 Roberto Clemente,All Grades,2014.0,All Students,63.0,279,38,60.3,23,36.5,1,1.6,1,1.6,2,3.2,01M015All Grades2015All Students,P.S. 015 Roberto Clemente,All Grades,2015.0,All Students,56.0,283,28,50.0,25,44.6,3,5.4,0,0.0,3,5.4,01M015All Grades2016All Students,P.S. 015 Roberto Clemente,All Grades,2016.0,All Students,51.0,293,23,45.1,18,35.3,10,19.6,0,0.0,10,19.6,01M015All Grades2017All Students,P.S. 015 Roberto Clemente,All Grades,2017.0,All Students,67.0,308,12,17.9,31,46.3,21,31.3,3,4.5,24,35.8,01M015All Grades2018All Students,P.S. 015 Roberto Clemente,All Grades,2018,All Students,67,610,5,7.5,17,25.4,31,46.3,14,20.9,45,67.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01M01932013All Students,01M019,P.S. 019 Asher Levy,3,2013.0,All Students,35.0,303,11,31.4,18,51.4,4,11.4,2,5.7,6,17.1,01M01932014All Students,P.S. 019 Asher Levy,3,2014.0,All Students,35.0,304,10,28.6,10,28.6,14,40.0,1,2.9,15,42.9,01M01932015All Students,P.S. 019 Asher Levy,3,2015.0,All Students,28.0,302,11,39.3,8,28.6,8,28.6,1,3.6,9,32.1,01M01932016All Students,P.S. 019 Asher Levy,3,2016.0,All Students,33.0,321,6,18.2,6,18.2,19,57.6,2,6.1,21,63.6,01M01932017All Students,P.S. 019 Asher Levy,3,2017.0,All Students,28.0,314,4,14.3,10,35.7,11,39.3,3,10.7,14,50.0,01M01932018All Students,P.S. 019 Asher Levy,3,2018.0,All Students,33.0,602,3,9.1,13,39.4,15,45.5,2,6.1,17,51.5,01M01942013All Students,P.S. 019 Asher Levy,4,2013.0,All Students,41.0,284,20,48.8,17,41.5,4,9.8,0,0.0,4,9.8,01M01942014All Students,P.S. 019 Asher Levy,4,2014.0,All Students,34.0,309,7,20.6,15,44.1,8,23.5,4,11.8,12,35.3,01M01942015All Students,P.S. 019 Asher Levy,4,2015.0,All Students,32.0,305,4,12.5,15,46.9,11,34.4,2,6.3,13,40.6,01M01942016All Students,P.S. 019 Asher Levy,4,2016.0,All Students,29.0,313,3,10.3,14,48.3,7,24.1,5,17.2,12,41.4,01M01942017All Students,P.S. 019 Asher Levy,4,2017.0,All Students,32.0,311,3,9.4,13,40.6,12,37.5,4,12.5,16,50.0,01M01942018All Students,P.S. 019 Asher Levy,4,2018.0,All Students,31.0,597,7,22.6,11,35.5,10,32.3,3,9.7,13,41.9,01M01952013All Students,P.S. 019 Asher Levy,5,2013.0,All Students,36.0,303,7,19.4,20,55.6,9,25.0,0,0.0,9,25.0,01M01952014All Students,P.S. 019 Asher Levy,5,2014.0,All Students,34.0,291,14,41.2,14,41.2,5,14.7,1,2.9,6,17.6,01M01952015All Students,P.S. 019 Asher Levy,5,2015.0,All Students,29.0,316,4,13.8,13,44.8,9,31.0,3,10.3,12,41.4,01M01952016All Students,P.S. 019 Asher Levy,5,2016.0,All Students,32.0,311,5,15.6,10,31.3,10,31.3,7,21.9,17,53.1,01M01952017All Students,P.S. 019 Asher Levy,5,2017.0,All Students,27.0,326,1,3.7,11,40.7,8,29.6,7,25.9,15,55.6,01M01952018All Students,P.S. 019 Asher Levy,5,2018.0,All Students,28.0,615,1,3.6,6,21.4,11,39.3,10,35.7,21,75.0,01M019All Grades2013All Students,P.S. 019 Asher Levy,All Grades,2013.0,All Students,112.0,296,38,33.9,55,49.1,17,15.2,2,1.8,19,17.0,01M019All Grades2014All Students,P.S. 019 Asher Levy,All Grades,2014.0,All Students,103.0,301,31,30.1,39,37.9,27,26.2,6,5.8,33,32.0,01M019All Grades2015All Students,P.S. 019 Asher Levy,All Grades,2015.0,All Students,89.0,308,19,21.3,36,40.4,28,31.5,6,6.7,34,38.2,01M019All Grades2016All Students,P.S. 019 Asher Levy,All Grades,2016.0,All Students,94.0,315,14,14.9,30,31.9,36,38.3,14,14.9,50,53.2,01M019All Grades2017All Students,P.S. 019 Asher Levy,All Grades,2017.0,All Students,87.0,316,8,9.2,34,39.1,31,35.6,14,16.1,45,51.7,01M019All Grades2018All Students,P.S. 019 Asher Levy,All Grades,2018,All Students,92,604,11,12.0,30,32.6,36,39.1,15,16.3,51,55.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN